# Generated by Django 5.2.8 on 2025-11-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RelayedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(db_index=True, max_length=66, unique=True)),
                ('from_address', models.CharField(max_length=42)),
                ('to_address', models.CharField(max_length=42)),
                ('data', models.TextField()),
                ('nonce', models.BigIntegerField()),
                ('tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'relayed_transactions',
                'indexes': [models.Index(fields=['from_address'], name='relayed_tra_from_ad_f2973b_idx'), models.Index(fields=['status'], name='relayed_tra_status_7889d4_idx')],
            },
        ),
    ]
